# уГЧуГнуГ│уГЧуГИуБохЕиф╜УчЪДуБкф╕жуБ│щаЖя╝ИуБКхе╜уБ┐уБзшк┐цХ┤хПпшГ╜я╝Й
format = """
$directory\
$git_branch\
$git_status\
$golang\
$cloud\
$line_break\
$character"""

# уГЗуВгуГмуВпуГИуГкуБошинхоЪя╝ИчЯнч╕ошбичд║уБкуБйя╝Й
[directory]
truncation_length = 3
fish_style_pwd_dir_length = 1

# Google Cloud шинхоЪя╝ИуГбуГ╝уГлуВвуГЙуГмуВ╣уВТщЪауБЧуБжуГЧуГнуВ╕уВзуВпуГИуБауБСуБлуБЧуБЯуВКуАБщЭЮшбичд║уБлуБзуБНуВЛя╝Й
[gcloud]
format = "on [тШБя╕П ($project)]($style) "
disabled = false # хоМхЕиуБлц╢ИуБЧуБЯуБДуБкуВЙ true

# AWS шинхоЪя╝ИуБУуВМуВВщЭЮшбичд║уБлуБЧуБЯуВКуАБуВ╖уГ│уГЧуГлуБлуБзуБНуВЛя╝Й
[aws]
format = "on [AWS($region)]($style) "
disabled = false # хоМхЕиуБлц╢ИуБЧуБЯуБДуБкуВЙ true

# GoуБошинхоЪя╝ИGoуБоуГЧуГнуВ╕уВзуВпуГИуБлуБДуВЛцЩВуБауБСуГРуГ╝уВ╕уГзуГ│уВТшбичд║я╝Й
[golang]
format = "via [ЁЯР╣ $version](bold cyan) "
