# Prompt
format = """
$directory\
$git_branch\
$git_status\
$golang\
$nodejs\
$python\
$aws\
$gcloud\
$line_break\
$character"""

# Directory
[directory]
truncate_to_repo = true
truncation_length = 5

# Golang
[golang]
format = "via [ğŸ¹ $version](bold cyan) "

# Node.js
[nodejs]
format = 'via [â¬¢ $version](bold green) '

# Python
[python]
format = 'via [ğŸ $version( \($virtualenv\))](bold yellow) '

# AWS
[aws]
format = '[â˜ï¸ $profile | $region]($style) '
style = "bold yellow"
disabled = false

# Google Cloud
[gcloud]
disabled = true

