# Prompt
format = """
$directory\
$git_branch\
$git_status\
$golang\
$nodejs\
$aws\
$gcloud\
$line_break\
$character"""

# Directory
[directory]
truncate_to_repo = true
truncation_length = 5

# Golang
[golang]
format = "via [üêπ $version](bold cyan) "

# Node.js
[nodejs]
format = 'via [‚¨¢ $version](bold green) '

# AWS
[aws]
format = '[‚òÅÔ∏è $profile | $region]($style) '
style = "bold yellow"
disabled = false

# Google Cloud
[gcloud]
disabled = true

